import { useCallback, useEffect, useState } from 'react';
import { DEFAULT_STATE } from './data';
import { clone, mergeState } from './lib';

const DESK_KEY = 'deskofme_state_v21';
const LEGACY_AUTH_KEY = 'deskofme_admin_v21';
const LEGACY_SESSION_KEY = 'deskofme_session_v21';
const SESSION_KEY = 'deskofme_global_session_v1';
const TOKEN_KEY = 'deskofme_publish_token_v21';
const AUTH_API_URL = (import.meta.env.VITE_AUTH_API_URL || '').replace(/\/$/, '');

function loadDesk() {
  try {
    const saved = JSON.parse(localStorage.getItem(DESK_KEY));
    if (saved?.config?.dataVersion < DEFAULT_STATE.config.dataVersion) {
      localStorage.removeItem(DESK_KEY);
      return clone(DEFAULT_STATE);
    }
    return mergeState(DEFAULT_STATE, saved);
  } catch {
    return clone(DEFAULT_STATE);
  }
}

export function useDeskState() {
  const [desk, setDesk] = useState(loadDesk);

  useEffect(() => {
    let active = true;
    fetch(`${import.meta.env.BASE_URL}desk-data.json?ts=${Date.now()}`, { cache: 'no-store' })
      .then((response) => response.ok ? response.json() : null)
      .then((remote) => {
        if (!active || !remote?.config) return;
        setDesk((current) => (remote.config.dataVersion || 0) > (current.config.dataVersion || 0)
          ? mergeState(DEFAULT_STATE, remote)
          : current);
      })
      .catch(() => {});
    return () => { active = false; };
  }, []);

  useEffect(() => {
    localStorage.setItem(DESK_KEY, JSON.stringify(desk));
  }, [desk]);

  const updateConfig = useCallback((next) => {
    setDesk((current) => ({
      ...current,
      config: typeof next === 'function' ? next(current.config) : { ...current.config, ...next },
    }));
  }, []);

  const updateItems = useCallback((next) => {
    setDesk((current) => ({ ...current, items: typeof next === 'function' ? next(current.items) : next }));
  }, []);

  const updateDecorations = useCallback((next) => {
    setDesk((current) => ({ ...current, decorations: typeof next === 'function' ? next(current.decorations) : next }));
  }, []);

  const replaceDesk = useCallback((next) => setDesk(mergeState(DEFAULT_STATE, next)), []);

  const resetDesk = useCallback(() => setDesk(clone(DEFAULT_STATE)), []);

  const publish = useCallback(async (token, configOverride = null) => {
    const publishConfig = configOverride || desk.config;
    const { owner, repo, branch } = publishConfig.publish;
    if (!token || !owner || !repo || !branch) throw new Error('请填写完整的 GitHub 发布信息');
    const nextDesk = {
      ...desk,
      config: { ...publishConfig, dataVersion: (desk.config.dataVersion || 0) + 1 },
    };
    const serializable = JSON.stringify(nextDesk, null, 2);
    const source = `// Generated by deskof.me publishing. Do not edit by hand.\nexport const publishedDeskState = ${serializable};\n`;
    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    };
    const putFile = async (targetBranch, path, rawContent, message) => {
      const fileApi = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;
      const existing = await fetch(`${fileApi}?ref=${encodeURIComponent(targetBranch)}`, { headers });
      let sha;
      if (existing.ok) sha = (await existing.json()).sha;
      else if (existing.status !== 404) throw new Error(`无法读取 ${path}（${existing.status}）`);
      const rawBytes = new TextEncoder().encode(rawContent);
      let rawBinary = '';
      rawBytes.forEach((byte) => { rawBinary += String.fromCharCode(byte); });
      const response = await fetch(fileApi, {
        method: 'PUT', headers,
        body: JSON.stringify({ message, content: btoa(rawBinary), branch: targetBranch, ...(sha ? { sha } : {}) }),
      });
      if (!response.ok) {
        const detail = await response.json().catch(() => ({}));
        throw new Error(detail.message || `发布 ${path} 失败（${response.status}）`);
      }
    };
    await putFile(branch, 'src/content.generated.js', source, `📤 Publish desk source v${nextDesk.config.dataVersion}`);
    await putFile('gh-pages', 'desk-data.json', `${serializable}\n`, `📤 Publish live desk data v${nextDesk.config.dataVersion}`);
    setDesk(nextDesk);
    return nextDesk.config.dataVersion;
  }, [desk]);

  return { desk, setDesk, updateConfig, updateItems, updateDecorations, replaceDesk, resetDesk, publish };
}

async function authRequest(path, options = {}) {
  if (!AUTH_API_URL) throw new Error('全局认证服务尚未配置，管理员入口已安全停用');
  const response = await fetch(`${AUTH_API_URL}${path}`, {
    ...options,
    cache: 'no-store',
    headers: { 'Content-Type': 'application/json', ...options.headers },
  });
  const body = await response.json().catch(() => ({}));
  return { response, body };
}

export function useAdmin() {
  const [isAdmin, setIsAdmin] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [authMode, setAuthMode] = useState(null);
  const [adminExists, setAdminExists] = useState(null);
  const [authReady, setAuthReady] = useState(false);
  const [authError, setAuthError] = useState('');

  useEffect(() => {
    let active = true;
    localStorage.removeItem(LEGACY_AUTH_KEY);
    localStorage.removeItem(LEGACY_SESSION_KEY);
    const token = localStorage.getItem(SESSION_KEY);

    const initialize = async () => {
      try {
        const status = await authRequest('/api/admin/status');
        if (!status.response.ok) throw new Error(status.body.error || '无法读取管理员状态');
        if (!active) return;
        setAdminExists(Boolean(status.body.adminExists));

        if (token) {
          const session = await authRequest('/api/admin/session', {
            headers: { Authorization: `Bearer ${token}` },
          });
          if (!active) return;
          if (session.response.ok && session.body.authenticated) setIsAdmin(true);
          else localStorage.removeItem(SESSION_KEY);
        }
        setAuthError('');
      } catch (error) {
        if (!active) return;
        localStorage.removeItem(SESSION_KEY);
        setIsAdmin(false);
        setAdminExists(null);
        setAuthError(error.message || '全局认证服务暂时不可用');
      } finally {
        if (active) setAuthReady(true);
      }
    };
    initialize();
    return () => { active = false; };
  }, []);

  useEffect(() => {
    if (!authReady || isAdmin || !new URLSearchParams(window.location.search).has('admin')) return;
    setAuthMode(adminExists === false ? 'setup' : 'login');
  }, [adminExists, authReady, isAdmin]);

  const setup = useCallback(async (password) => {
    if (!authReady || adminExists !== false) {
      return { ok: false, error: adminExists ? '管理员已存在，只能登录' : authError || '正在确认管理员状态' };
    }
    if (password.length < 8) return { ok: false, error: '密码至少需要 8 个字符' };
    try {
      const { response, body } = await authRequest('/api/admin/register', {
        method: 'POST', body: JSON.stringify({ password }),
      });
      if (!response.ok) {
        if (response.status === 409 || body.code === 'ADMIN_ALREADY_EXISTS') {
          setAdminExists(true);
          setAuthMode('login');
        }
        return { ok: false, error: body.error || '创建管理员失败' };
      }
      localStorage.setItem(SESSION_KEY, body.token);
      setAdminExists(true);
      setIsAdmin(true);
      setAuthMode(null);
      return { ok: true };
    } catch (error) {
      return { ok: false, error: error.message || '全局认证服务暂时不可用' };
    }
  }, [adminExists, authError, authReady]);

  const login = useCallback(async (password) => {
    try {
      const { response, body } = await authRequest('/api/admin/login', {
        method: 'POST', body: JSON.stringify({ password }),
      });
      if (!response.ok) {
        if (response.status === 404 || body.code === 'ADMIN_NOT_FOUND') {
          setAdminExists(false);
          setAuthMode('setup');
        }
        return { ok: false, error: body.error || '登录失败' };
      }
      localStorage.setItem(SESSION_KEY, body.token);
      setAdminExists(true);
      setIsAdmin(true);
      setAuthMode(null);
      return { ok: true };
    } catch (error) {
      return { ok: false, error: error.message || '全局认证服务暂时不可用' };
    }
  }, []);

  const logout = useCallback(() => {
    localStorage.removeItem(SESSION_KEY);
    setIsAdmin(false);
    setEditMode(false);
  }, []);

  const toggleEdit = useCallback(() => {
    if (isAdmin) setEditMode((value) => !value);
  }, [isAdmin]);

  return {
    isAdmin, editMode, authMode, adminExists, authReady, authError, setup, login, logout, toggleEdit,
    showLogin: () => setAuthMode(adminExists === false ? 'setup' : 'login'),
    showSetup: () => { if (authReady && adminExists === false) setAuthMode('setup'); },
    closeAuth: () => setAuthMode(null),
  };
}

export function usePublishToken() {
  const [token, setTokenState] = useState(() => localStorage.getItem(TOKEN_KEY) || '');
  const setToken = useCallback((value) => {
    setTokenState(value);
    if (value) localStorage.setItem(TOKEN_KEY, value);
    else localStorage.removeItem(TOKEN_KEY);
  }, []);
  return [token, setToken];
}

export function useMobile() {
  const [mobile, setMobile] = useState(() => window.matchMedia('(max-width: 720px), (pointer: coarse)').matches);
  useEffect(() => {
    const query = window.matchMedia('(max-width: 720px), (pointer: coarse)');
    const update = () => setMobile(query.matches);
    query.addEventListener('change', update);
    return () => query.removeEventListener('change', update);
  }, []);
  return mobile;
}
