import { useCallback, useEffect, useState } from 'react';
import { DEFAULT_STATE } from './data';
import { clone, mergeState } from './lib';

const DESK_KEY = 'deskofme_state_v21';
const AUTH_KEY = 'deskofme_admin_v21';
const SESSION_KEY = 'deskofme_session_v21';
const TOKEN_KEY = 'deskofme_publish_token_v21';
const SALT = 'deskof.me::paper-computer::2026';

function loadDesk() {
  try {
    const saved = JSON.parse(localStorage.getItem(DESK_KEY));
    if (saved?.config?.dataVersion < DEFAULT_STATE.config.dataVersion) {
      localStorage.removeItem(DESK_KEY);
      return clone(DEFAULT_STATE);
    }
    return mergeState(DEFAULT_STATE, saved);
  } catch {
    return clone(DEFAULT_STATE);
  }
}

export function useDeskState() {
  const [desk, setDesk] = useState(loadDesk);

  useEffect(() => {
    let active = true;
    fetch(`${import.meta.env.BASE_URL}desk-data.json?ts=${Date.now()}`, { cache: 'no-store' })
      .then((response) => response.ok ? response.json() : null)
      .then((remote) => {
        if (!active || !remote?.config) return;
        setDesk((current) => (remote.config.dataVersion || 0) > (current.config.dataVersion || 0)
          ? mergeState(DEFAULT_STATE, remote)
          : current);
      })
      .catch(() => {});
    return () => { active = false; };
  }, []);

  useEffect(() => {
    localStorage.setItem(DESK_KEY, JSON.stringify(desk));
  }, [desk]);

  const updateConfig = useCallback((next) => {
    setDesk((current) => ({
      ...current,
      config: typeof next === 'function' ? next(current.config) : { ...current.config, ...next },
    }));
  }, []);

  const updateItems = useCallback((next) => {
    setDesk((current) => ({ ...current, items: typeof next === 'function' ? next(current.items) : next }));
  }, []);

  const updateDecorations = useCallback((next) => {
    setDesk((current) => ({ ...current, decorations: typeof next === 'function' ? next(current.decorations) : next }));
  }, []);

  const replaceDesk = useCallback((next) => setDesk(mergeState(DEFAULT_STATE, next)), []);

  const resetDesk = useCallback(() => setDesk(clone(DEFAULT_STATE)), []);

  const publish = useCallback(async (token, configOverride = null) => {
    const publishConfig = configOverride || desk.config;
    const { owner, repo, branch } = publishConfig.publish;
    if (!token || !owner || !repo || !branch) throw new Error('请填写完整的 GitHub 发布信息');
    const nextDesk = {
      ...desk,
      config: { ...publishConfig, dataVersion: (desk.config.dataVersion || 0) + 1 },
    };
    const serializable = JSON.stringify(nextDesk, null, 2);
    const source = `// Generated by deskof.me publishing. Do not edit by hand.\nexport const publishedDeskState = ${serializable};\n`;
    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
    };
    const putFile = async (targetBranch, path, rawContent, message) => {
      const fileApi = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;
      const existing = await fetch(`${fileApi}?ref=${encodeURIComponent(targetBranch)}`, { headers });
      let sha;
      if (existing.ok) sha = (await existing.json()).sha;
      else if (existing.status !== 404) throw new Error(`无法读取 ${path}（${existing.status}）`);
      const rawBytes = new TextEncoder().encode(rawContent);
      let rawBinary = '';
      rawBytes.forEach((byte) => { rawBinary += String.fromCharCode(byte); });
      const response = await fetch(fileApi, {
        method: 'PUT', headers,
        body: JSON.stringify({ message, content: btoa(rawBinary), branch: targetBranch, ...(sha ? { sha } : {}) }),
      });
      if (!response.ok) {
        const detail = await response.json().catch(() => ({}));
        throw new Error(detail.message || `发布 ${path} 失败（${response.status}）`);
      }
    };
    await putFile(branch, 'src/content.generated.js', source, `📤 Publish desk source v${nextDesk.config.dataVersion}`);
    await putFile('gh-pages', 'desk-data.json', `${serializable}\n`, `📤 Publish live desk data v${nextDesk.config.dataVersion}`);
    setDesk(nextDesk);
    return nextDesk.config.dataVersion;
  }, [desk]);

  return { desk, setDesk, updateConfig, updateItems, updateDecorations, replaceDesk, resetDesk, publish };
}

async function hashPassword(password) {
  const bytes = new TextEncoder().encode(`${password}:${SALT}`);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

export function useAdmin() {
  const [isAdmin, setIsAdmin] = useState(() => localStorage.getItem(SESSION_KEY) === 'admin');
  const [editMode, setEditMode] = useState(false);
  const [authMode, setAuthMode] = useState(null);
  const hasPassword = Boolean(localStorage.getItem(AUTH_KEY));

  useEffect(() => {
    if (new URLSearchParams(window.location.search).has('admin') && !isAdmin) setAuthMode('login');
  }, [isAdmin]);

  const setup = useCallback(async (password) => {
    if (password.length < 4) return { ok: false, error: '密码至少需要 4 个字符' };
    const hash = await hashPassword(password);
    localStorage.setItem(AUTH_KEY, JSON.stringify({ hash, createdAt: Date.now() }));
    localStorage.setItem(SESSION_KEY, 'admin');
    setIsAdmin(true);
    setAuthMode(null);
    return { ok: true };
  }, []);

  const login = useCallback(async (password) => {
    const record = localStorage.getItem(AUTH_KEY);
    if (!record) return { ok: false, error: '本浏览器尚未设置管理员密码' };
    try {
      const { hash } = JSON.parse(record);
      if (await hashPassword(password) !== hash) return { ok: false, error: '密码不正确' };
      localStorage.setItem(SESSION_KEY, 'admin');
      setIsAdmin(true);
      setAuthMode(null);
      return { ok: true };
    } catch {
      return { ok: false, error: '管理员记录已损坏，请清理本站数据后重试' };
    }
  }, []);

  const logout = useCallback(() => {
    localStorage.removeItem(SESSION_KEY);
    setIsAdmin(false);
    setEditMode(false);
  }, []);

  const toggleEdit = useCallback(() => {
    if (isAdmin) setEditMode((value) => !value);
  }, [isAdmin]);

  return {
    isAdmin, editMode, authMode, hasPassword, setup, login, logout, toggleEdit,
    showLogin: () => setAuthMode('login'), showSetup: () => setAuthMode('setup'), closeAuth: () => setAuthMode(null),
  };
}

export function usePublishToken() {
  const [token, setTokenState] = useState(() => localStorage.getItem(TOKEN_KEY) || '');
  const setToken = useCallback((value) => {
    setTokenState(value);
    if (value) localStorage.setItem(TOKEN_KEY, value);
    else localStorage.removeItem(TOKEN_KEY);
  }, []);
  return [token, setToken];
}

export function useMobile() {
  const [mobile, setMobile] = useState(() => window.matchMedia('(max-width: 720px), (pointer: coarse)').matches);
  useEffect(() => {
    const query = window.matchMedia('(max-width: 720px), (pointer: coarse)');
    const update = () => setMobile(query.matches);
    query.addEventListener('change', update);
    return () => query.removeEventListener('change', update);
  }, []);
  return mobile;
}
